### ISSUE TITLE
TODO: API Endpoints

### ISSUE THREAD

**Issue by bombnp** [bombnp/cutuball74-backend#1]
**Pre-registration Endpoints**

- [x] /api/register
- [x] /api/getuser

**Pre-registration Endpoints**

- [x] /api/checkin
- [x] /api/getticket

**Admin Endpoints**

- [x] /api/admin/getusers
- [x] /api/admin/query
- [x] /api/admin/random
- [x] /api/admin/randomhistory
- [x] /api/admin/clearhistory
- [x] /api/admin/edit
- [x] /api/admin/getstat
- [x] /api/admin/delete

**Authentication Endpoints**

- [x] /token

**Comment by bombnp** [comment]
All done.
